abstract class ElectricityStates{}

class InitialElectricityState extends ElectricityStates{}

class UploadIDImageLoading extends ElectricityStates{}
class UploadIDImageSuccess extends ElectricityStates{}
class UploadIDImageError extends ElectricityStates{}

class UploadContractImageLoading extends ElectricityStates{}
class UploadContractImageSuccess extends ElectricityStates{}
class UploadContractImageError extends ElectricityStates{}

class UploadReceiptImageLoading extends ElectricityStates{}
class UploadReceiptImageSuccess extends ElectricityStates{}
class UploadReceiptImageError extends ElectricityStates{}

class UploadMaintenanceReceiptImageLoading extends ElectricityStates{}
class UploadMaintenanceReceiptImageSuccess extends ElectricityStates{}
class UploadMaintenanceReceiptImageError extends ElectricityStates{}

class UploadImageMeterLoading extends ElectricityStates{}
class UploadImageMeterSuccess extends ElectricityStates{}
class UploadImageMeterError extends ElectricityStates{}

class UploadImageMeterReceiptLoading extends ElectricityStates{}
class UploadImageMeterReceiptSuccess extends ElectricityStates{}
class UploadImageMeterReceiptError extends ElectricityStates{}

class ChangeItemInstallation extends ElectricityStates{}

class SendElectricityInstallationLoading extends ElectricityStates{}
class SendElectricityInstallationSuccess extends ElectricityStates{}
class SendElectricityInstallationError extends ElectricityStates{}

class SendMaintenanceRequestLoading extends ElectricityStates{}
class SendMaintenanceRequestSuccess extends ElectricityStates{}
class SendMaintenanceRequestError extends ElectricityStates{}

class SendElectricityReadingLoading extends ElectricityStates{}
class SendElectricityReadingSuccess extends ElectricityStates{}
class SendElectricityReadingError extends ElectricityStates{}

class SendRemoveElectricityMeterLoading extends ElectricityStates{}
class SendRemoveElectricityMeterSuccess extends ElectricityStates{}
class SendRemoveElectricityMeterError extends ElectricityStates{}

class GetElectricityInstallationListLoading extends ElectricityStates{}
class GetElectricityInstallationListSuccess extends ElectricityStates{}
class GetElectricityInstallationListError extends ElectricityStates{}

class GetElectricityMaintenanceListLoading extends ElectricityStates{}
class GetElectricityMaintenanceListSuccess extends ElectricityStates{}
class GetElectricityMaintenanceListError extends ElectricityStates{}

class GetElectricityMeterReadingLoading extends ElectricityStates{}
class GetElectricityMeterReadingSuccess extends ElectricityStates{}
class GetElectricityMeterReadingError extends ElectricityStates{}

class GetRemoveElectricityMeterLoading extends ElectricityStates{}
class GetRemoveElectricityMeterSuccess extends ElectricityStates{}
class GetRemoveElectricityMeterError extends ElectricityStates{}